<?php
    

     $om = \Magento\Framework\App\ObjectManager::getInstance();
     $eavConfig = $om->get('\Magento\Eav\Model\Config');
     $customerSession = $om->create('Magento\Customer\Model\Session');
     if($customerSession->isLoggedIn()) {
         $cusid =  $customerSession->getCustomer()->getId();
         $cusname =  $customerSession->getCustomer()->getFirstname().' '.$customerSession->getCustomer()->getLastname();
        $cusemail =  $customerSession->getCustomer()->getEmail();
     }else{
         $cusid= 0;
         $cusname = '';
        $cusemail = '';
     }
     $helper = $this->helper('pws\panel\Helper\Data');
     //$values = $helper->getGroupListById($cusid);
     //$cuttingid = $this->getRequest()->getParam('id');
     $productslimit = $block->getProductCollection();
     $products =$block->getProductCollectionAll();
     
     $panelid = $this->getRequest()->getParam('id');
     $cuttingcollection = $helper->getCuttingcollection($panelid);
     $uncutcollection = $helper->getUncutcollection($panelid);
     $panelload = $om->create('Pws\Panel\Model\Panel')->load($panelid);
     $quotestatus = $panelload->getQuotestatus();
     
     
     $materal = $materialcode = $length = $width = $paneldescription = $specialnotes = $edgingprofile = $grainmatiching = $sku = $proid = $status = $cabinetno = $edgingbanding = $edgingbandingop = $edgingbandingpro = $thickness= $lastentry = $image = $lengthval= $widthval=$boardtype=$manufacturer=$edgetype=$radius= '';
     $priceval =0;
     $qty = 1;
     $cqty = 1;
     
     
     $cutlineid = $this->getRequest()->getParam('cid');
     if($cutlineid){
          $created = $om->create('Pws\Panel\Model\Cutlist')->load($cutlineid);
     }
     
     $uncutid = $this->getRequest()->getParam('uid');
     if($uncutid){
          $ucreated = $om->create('Pws\Panel\Model\Uncut')->load($uncutid);
     }
     $sid = $this->getRequest()->getParam('sid');
     if($sid){
          $created = $om->create('Pws\Panel\Model\Cutlist')->load($sid);
     }
     $price = '------';
     if(!empty($created)){
          $material = $created->getMaterial();
          $product = $om->create('Magento\Catalog\Model\Product')->load($material);
          $widthval = $product->getResource()->getAttribute('width')->getFrontend()->getValue($product)-30;
          $lengthval = $product->getResource()->getAttribute('length')->getFrontend()->getValue($product)-30;
          $materialcode = $created->getMaterialcode();
          $length = $created->getLength();
          $width = $created->getWidth();
          $thickness = $created->getThickness();
          $paneldescription = $created->getPaneldescription();
          $specialnotes = $created->getSpecialnotes();
          $edgingprofile = $created->getEdgingprofile();
          $grainmatiching = $created->getGrainmatching();
          $image = $created->getImage();
          $sku = $created->getSku();
          $proid = $created->getProid();
          $status = $created->getStatus();
          $cabinetno = $created->getCabinetno();
          $edgingbanding = $created->getEdgingbanding();
          $edgingbandingop =$created->getEdgingbandingop();
          $edgingbandingpro =$created->getEdgingprofile();
          $qty = $created->getQty();
          
          if($created->getPricefull()):
               $price = $created->getPricefull();
               $priceval = $price;
          endif;
          
          
          //for edging validation
          $boardtype = $product->getBoardType();
          $manufacturer = $product->getManufacturer();
          if($boardtype == '9699'){
          if($manufacturer == '308' || $manufacturer == '307' || $manufacturer == '9773'){ //MDF + MEDITE, FINSA, PRIMED MDF
              $edgetype = '1';
              $radius = '1,2,3';
          }
          }elseif($boardtype == '9698'){//FR MDF +
              $edgetype = '1';
              $radius = '1,2,3';
              
          }elseif($boardtype == '9702'){//FR MDF + all
              $edgetype = '1';
              $radius = '1,2,3';
              
          }elseif($boardtype == '9700'){//Melamine Faced MDF
              if($manufacturer == '445'){//KRONOSPAN
                  $edgetype = '2,3,4,5';
                  $radius = '1,2,3';
              }elseif($boardtype=='995'){//Alvic
                  $edgetype = '2';
                  $radius = '1,2';
              }elseif($boardtype=='309'){//Egger
      
                  $edgetype = '2,4';
                  $radius = '1,2';
              }elseif($boardtype=='309'){//Unilin
                  $edgetype = '2,3';
                  $radius = '1,2,3';
              }        
              
          }elseif($boardtype == '9701'){ //mfc
              if($manufacturer == '309' || $manufacturer == '995' || $manufacturer == '445'){ //Egger,Alvic,Kronospan
                  $edgetype = '2,3,4,5';
                  $radius = '1,2,3';
              }elseif($manufacturer == '1166' || $manufacturer == '9783'){//XyloCleaf,Diplos
                  $edgetype = '2';
                  $radius = '1,2';
                  
              }
          }elseif($boardtype == '9719'){//Pre-veneered Boards+Galtee
              $edgetype = '6,7';
              $radius = '1,2,3';
          }
     }
   
?>

<div class="blue-title-sec">
    <div class="container">              
        <div class="row align-items-center my-address-row">
          <div class="col-md-12 col-lg-5">
          <?php if(!empty($created)){ ?>
               <h2 class="mb-0"><?= $block->escapeHtml(__('Edit Cutting List')) ?></h2>
          <?php }elseif(!empty($ucreated)){ ?>
               <h2 class="mb-0"><?= $block->escapeHtml(__('Edit Product')) ?></h2>
          <?php }else{ ?>
               <h2 class="mb-0"><?= $block->escapeHtml(__('Create Cutting/Product List')) ?></h2>
          <?php } ?>
          <span class="greentext">Cutting costs are included in all board prices</span>
          </div>
          <div class="col-md-12 col-lg-7">
          <p class="mb-0"><?= $block->escapeHtml(__('Please fill the form below for the Cutting List- ')) ?> <?php echo $panelload->getName(); ?><a style="float: right;color: #fff; text-decoration: underline;" href="<?php echo $this->getUrl('panel/panel/printpdf').'id/'.$panelid; ?>">Print Project</a></p>

          </div>
        </div>           
    </div>
</div>
<div class="main-content-sec grey-bg-sec">

<div class="container">
<div class="row justify-content-center">       
<div class="col-md-12 col-lg-12"> 
<div class="my-address-form">
     <div class="table-responsive">
          <table class="cutlist-table">
               <caption>Cutting List</caption>
               <thead>
                    <th>S. No.</th>
                    <th>Part Description</th>
                    <th>Material</th>
                    <th>Material Code</th>
                    
                    <th>Length (mm)</th>
                    <th>Width (mm)</th>
                    <th>Qty</th>
                    <th>Edge Top</th>
                    <th>Edge Bottom</th>
                    <th>Edge Left</th>
                    <th>Edge Right</th>
                    <th>Cabinet No.</th>
                    <th>Grain Matching</th>
                    <th>Actions</th>
               </thead>
               <tbody>
               <?php $counter=1;foreach($cuttingcollection as $cutting){
                    $material = $cutting->getMaterial();
                    $product = $om->create('Magento\Catalog\Model\Product')->load($material);
                    $material = $product->getName();
                    $edgebanding = $cutting->getEdgingbanding();
                    $bottom = $top = $left = $right = '';
					$edgebanding = strtolower($edgebanding);
					$edgeoption = $cutting->getEdgingbandingop();
                         if($edgeoption==1){
                            $label = '0.6mm MDF preparation tape';
                         }else if($edgeoption==2){
                              $label = '1mm Standard ABS matching';
                         }else if($edgeoption==3){
                              $label = '2mm Standard ABS matching';
                         }else if($edgeoption==4){
                              $label = '1mm Airtec Matching';
                         }else if($edgeoption==5){
                              $label = '2mm Airtec Matching';
                         }else if($edgeoption==6){
                              $label = '1mm Wood Veneer Matching';
                         }else if($edgeoption==7){
                              $label = '2mm Wood Veneer Matching';
                         }
					$edgeprofile = $cutting->getEdgingprofile();
                         
                         if($edgeprofile==1){
                            $slabel = 'Square';
                         }else if($edgeprofile==2){
                              $slabel = '1mm Radius';
                         }else if($edgeprofile==3){
                              $slabel = '2mm Radius';
                         }
                         
					if (strpos($edgebanding, 'bottom') !== false) {
						$bottom = '<b>Option-</b> '.$label.' <b>Radius- </b>'.$slabel;
					}
					if (strpos($edgebanding, 'top') !== false) {
						$top = '<b>Option-</b> '.$label.' <b>Radius- </b>'.$slabel;
					}
					if (strpos($edgebanding, 'left') !== false) {
						$left = '<b>Option-</b> '.$label.' <b>Radius- </b>'.$slabel;
					}
					if (strpos($edgebanding, 'right') !== false) {
						$right = '<b>Option-</b> '.$label.' <b>Radius- </b>'.$slabel;
					} ?>
                    <tr>
                         <td id="tsno"><?php echo $counter; ?></td>
                         <td id="tpaneldescription"><?php echo $cutting->getPaneldescription(); ?></td>
                         <td id="tmaterial"><?php echo $material; ?></td>
                         <td id="tproductcode"><?php echo $cutting->getMaterialcode(); ?></td>
                         <td id="tlength"><?php echo $cutting->getLength(); ?></td>
                         <td id="twidth"><?php echo $cutting->getWidth(); ?></td>
                         <td id="tqty"><?php echo $cutting->getQty(); ?></td>
                         <td id="tedgingtop"><?php echo $top; ?></td>
                         <td id="tedgingbottom"><?php echo $bottom; ?></td>
                         <td id="tedgingleft"><?php echo $left; ?></td>
                         <td id="tedgingright"><?php echo $right; ?></td>
                         <td id="tcabinetno"><?php echo $cutting->getCabinetno(); ?></td>
                         <td id="tgrain"><?php echo $cutting->getGrainmatching(); ?></td>
                         <td id="tActions"><?php if($quotestatus == 'Created'): ?> <a title="Edit Cutting List" href="<?php echo $this->getUrl('panel/cutting/add').'id/'.$panelid.'/cid/'.$cutting->getCutlineId(); ?>"><i class="far fa-edit"></i>
</a><a title="Delete Cutting List" style="margin-left:10px" href="<?php echo $this->getUrl('panel/cutting/delete').'id/'.$cutting->getCutlineId().'/pid/'.$panelid; ?>"><i class="fas fa-trash" aria-hidden="true"></i>
</a><?php else: ?> <a href="#cutlistpopup" onclick="cuttinglist(<?php echo $cutting->getCutlineId(); ?>);" data-toggle="modal" title="View Cutting List">View</a> <?php endif; ?></td>
                    </tr>
               <?php $lastentry = $cutting->getCutlineId();$counter++;}; ?>
               </tbody>
          </table>
          </div>

          <div class="table-responsive">
          <table class="cutlist-table">
               <caption>Full Sheets</caption>
               <thead>
                    <th>S. No.</th>
                    <th>Part Description</th>
                    <th>Material Code</th>                    
                    <th>Length (mm)</th>
                    <th>Width (mm)</th>
                    <th>Thickness (mm)</th>
                    <th>Qty</th>
                    <th>Actions</th>
               </thead>
               <tbody>
               <?php $counter=1;foreach($uncutcollection as $uncut){
                    ?>
                    <tr>
                         <td><?php echo $counter; ?></td>
                         <td><?php echo $uncut->getCpaneldescription(); ?></td>
                         <td><?php echo $uncut->getMaterialcode(); ?></td>
                         <td><?php echo $uncut->getClength(); ?></td>
                         <td><?php echo $uncut->getCwidth(); ?></td>
                         <td><?php echo $uncut->getThickness(); ?></td>
                         <td><?php echo $uncut->getCqty(); ?></td>
                         <td><?php if($quotestatus == 'Created'): ?> <a title="Edit Product List" href="<?php echo $this->getUrl('panel/cutting/add').'id/'.$panelid.'/uid/'.$uncut->getUncutId(); ?>"><i class="far fa-edit"></i>
</a><a title="Delete Product" style="margin-left:10px" href="<?php echo $this->getUrl('panel/uncut/delete').'id/'.$uncut->getUncutId().'/pid/'.$panelid; ?>"><i class="fas fa-trash" aria-hidden="true"></i>
</a><?php else: ?> <!--<a href="#imviypopup" onclick="uncutlist(<?php echo $uncut->getUncutId(); ?>);" data-toggle="modal" title="View Cutting List">View</a>--> <?php endif; ?></td>
                    </tr>
               <?php $counter++;}; ?>
               </tbody>
          </table>
          </div>


          <?php if($quotestatus == 'Created' && ($cuttingcollection->getSize() >0 || $uncutcollection->getSize()>0)): ?>
          <div class="">
               <form class="form"
                    action="<?php /* @escapeNotVerified */ echo $block->getFormQuoteAction(); ?>"
                    id="cutlist_form_quote"
                    enctype="multipart/form-data"
                    method="post">
                    <input type="hidden" name="panel_id" value="<?php echo $panelid; ?>" />
                    <input type="hidden" name="quotestatus" value="Request Sent" />
                    <input type="hidden" name="url_key" value="<?php echo $cusid; ?>" />
                    <input type="hidden" name="customer_name" value="<?php echo $cusname; ?>" />
                    <input type="hidden" name="customer_email" value="<?php echo $cusemail; ?>" />
                    <input type="hidden" name="stores[]" value="0" />
                    <input type="hidden" name="mail_send" value="1" />
                    <div class="container">
                    <div class="row">
                    <div class="field required form-group col-md-12 col-lg-12 d-flex align-items-center">
                         
                    <label class="mr-5 mb-0" for="offcuts"><?php /* @escapeNotVerified */ echo __('Do you wish to keep your Off-Cuts?') ?><span style="color: red;">
                    <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
                    
                    <div class="d-flex align-items-center">
                         <span class="d-flex align-items-center"><input id="offyes" required type="radio" class="required-entry mt-0" name="offcuts" value="Yes" data-validate="{required:true}"><label for="offyes" class="mr-4">Yes</label></span>
                         <span class="d-flex align-items-center"><input id="offno" required type="radio" class="required-entry mt-0" name="offcuts" value="No" data-validate="{required:true}"><label for="offno" class="mr-4">No</label></span>
                    </div>

                    </div>
                    <div class="field required form-group col-md-12 col-lg-6 d-flex align-items-center fdirectionc">
                         
                    <label class="mr-5 mb-0" for="offcuts"><?php /* @escapeNotVerified */ echo __('Shipping Options') ?><span style="color: red;">
                    <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
                    
                    <div class="d-flex align-items-center deliverysection fdirectionc">
                         <span class="d-flex align-items-center"><input id="collection" required type="radio" class="required-entry mt-0" name="delivery" value="collection" data-validate="{required:true}"><label for="collection" class="mr-4">Collection</label></span>
                         <span class="d-flex align-items-center"><input id="delivery" required type="radio" class="required-entry mt-0" name="delivery" value="delivery" data-validate="{required:true}"><label for="delivery" class="mr-5">Delivery</label></span>
                         <input id="postcode" style="display: none; max-width: 140px;" type="text" name="postcode" value="" autocomplete="off" placeholder="Postcode" class="ml-5">
                    </div>
                    </div>
                    
                    <div class="field required form-group col-md-12 col-lg-6" >
                         <div class="d-flex align-items-center">
                              
                              <button type="submit" style="background: #255792;" class="btn btn-secondary ml-auto"><span>Submit For Quote</span></button>
                         </div>
                    </div>
                    </div>
                    </div>
                    
                    
                    
               </form>
          </div>
          <?php endif; ?>
</div>
</div>
</div>
</div>
     
<div class="container">
<div class="row justify-content-center">       
<div class="col-md-12 col-lg-12"> 
<div class="my-address-form">
          
<?php if($quotestatus == 'Created'): ?>
<?php if(!empty($ucreated)): 
$sku = $ucreated->getSku();
$proid = $ucreated->getProid();
$cqty = $ucreated->getCqty();
$materialcode = $ucreated->getMaterialcode();
$length = $ucreated->getClength();
$width = $ucreated->getCwidth();
$thickness = $ucreated->getThickness();
$priceval = $ucreated->getPricefull();
$paneldescription = $ucreated->getCpaneldescription();
?>

     <form class="form"
      action="<?php /* @escapeNotVerified */ echo str_replace('cutting','uncut',$block->getFormAction()); ?>"
      id="cutlist_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
     <input type="hidden" name="url_key" value="<?php echo $cusid; ?>" />
     <input type="hidden" name="customer_name" value="<?php echo $cusname; ?>" />
     <input type="hidden" name="customer_email" value="<?php echo $cusemail; ?>" />
     <input type="hidden" name="status" value="Created" />
     <input type="hidden" name="panel_id" value="<?php echo $panelid; ?>" />
     <input type="hidden" name="pricefull" id="pricefull" value="<?php echo $priceval; ?>" />
     <?php if($uncutid): ?>
     <input type="hidden" name="uncut_id" value="<?php echo $uncutid; ?>" />
     <?php endif; ?>
     <input type="hidden" id="sku" name="sku" value="<?php echo $sku; ?>" />
     <input type="hidden" name="proid" id="proid" value="<?php echo $proid; ?>" />
     <fieldset class="fieldset" style="margin-bottom: 20px;">
        
        <div class="row">
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="panel_image"><?php /* @escapeNotVerified */ echo __('Material:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <select class="form-control" id="material" name="material">
                    <option>--Please select a Material First--</option>
                   <?php if(count($products)>0){ ?>
                   <?php foreach($products as $product){
                         $productid = $product->getId();
                    
                    ?>
                   <option <?php if($proid == $productid){;echo 'selected=selected';}; ?> value="<?php echo $productid; ?>"><?php echo $product->getName(); ?></option>
                   <?php } ?>
                   <?php } ?>
                </select>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="materialcode"><?php /* @escapeNotVerified */ echo __('Material Code:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control" >
               <input id="materialcode" name="materialcode" title="<?php /* @escapeNotVerified */ echo __('Your Panel Name:') ?>" value="<?php echo $materialcode; ?>" class="form-control input-text" type="text" readonly data-validate="{required:true}"/>
            </div>
        </div>

             <div class="container showdiv mb-4">
               <div class="row">
                    <div class="col-md-12 col-lg-6">
                         <p><strong>Length (mm): </strong><span id="uncutlength"><?php echo $length; ?></span></p><p><strong>Width (mm): </strong><span id="uncutwidth"><?php echo $width; ?></span></p><p><strong>Thickness (mm): </strong><span id="uncutthickness"><?php echo $thickness; ?></span></p><p><strong>Price (Ex VAT): </strong><span id="uncutprice"><?php echo $priceval; ?></span></p>
                         <input type="hidden" id="clength" name="clength" value="<?php echo $length; ?>"/>
                         <input type="hidden" id="cwidth" name="cwidth" value="<?php echo $width; ?>"/>
                         <input type="hidden" id="cpaneldescription" name="cpaneldescription" value="<?php echo $paneldescription; ?>"/>
                    </div>
                    <div class="field required form-group col-md-12 col-lg-1 showdiv" style="padding-top: 5px;">
                     <label for="thickness"><?php /* @escapeNotVerified */ echo __('Qty:') ?><span style="color: red;">
                         <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
                     </div>
                    <div class="field required form-group col-md-12 col-lg-1 showdiv">
                         
                         <div class="control">
                        
                         <input name="cqty" id="cqty" title="<?php /* @escapeNotVerified */ echo __('Qty:') ?>" value="<?php echo $cqty; ?>" class="form-control input-text validate-greater-than-zero" data-validate="{required:true}" type="text"/>
                         </div>
                     </div>
                     <div class="field required form-group col-md-12 col-lg-4">
                    <button type="submit" style="background: #255792; float: left;" class="btn btn-secondary pull-right"><span>Add For Quote</span></button>
          
                    </div>
               </div>
             </div>
        
        </div>

    </fieldset>
   
     <?php if(isset($_SERVER['HTTP_REFERER'])){ ?>
          <div class="secondary form-btn-set ml-3"><a class="btn btn-outline-secondary" href="<?php echo $_SERVER['HTTP_REFERER']; ?>" title="Go back">Go Back</a></div>
     <?php } ?>
</form>
<?php else: ?>
<form class="form"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="cutlist_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
     <input type="hidden" name="url_key" value="<?php echo $cusid; ?>" />
     <input type="hidden" name="customer_name" value="<?php echo $cusname; ?>" />
     <input type="hidden" name="customer_email" value="<?php echo $cusemail; ?>" />
     <input type="hidden" name="status" value="Created" />
     <input type="hidden" name="panel_id" value="<?php echo $panelid; ?>" />
     <input type="hidden" name="pricefull" id="pricefull" value="<?php echo $priceval; ?>" />
     <?php if($cutlineid): ?>
     <input type="hidden" name="cutline_id" value="<?php echo $cutlineid; ?>" />
     <?php endif; ?>
     <input type="hidden" id="sku" name="sku" value="<?php echo $sku; ?>" />
     <input type="hidden" name="proid" id="proid" value="<?php echo $proid; ?>" />
     <fieldset class="fieldset" style="margin-bottom: 20px;">
        <a class="btn btn-secondary mb-4" onclick="searchproduct()" href="#productpopup" data-toggle="modal">For Material Code Please select Product Here</a>
        <?php if($lastentry): ?>
        <a class="btn btn-secondary mb-4 ml-md-5" href="<?php echo $this->getUrl('panel/cutting/add').'id/'.$panelid.'/sid/'.$lastentry; ?>">Use Same Entry As Last</a>
        <?php endif; ?>
        <div class="row">
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="panel_image"><?php /* @escapeNotVerified */ echo __('Material:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <select class="form-control" id="material" name="material">
                    <option>--Please select a Material First--</option>
                   <?php if(count($products)>0){ ?>
                   <?php foreach($products as $product){
                         $productid = $product->getId();
                    
                    ?>
                   <option <?php if($proid == $productid){;echo 'selected=selected';}; ?> value="<?php echo $productid; ?>"><?php echo $product->getName(); ?></option>
                   <?php } ?>
                   <?php } ?>
                </select>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="materialcode"><?php /* @escapeNotVerified */ echo __('Material Code:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control" >
               <input id="materialcode" name="materialcode" title="<?php /* @escapeNotVerified */ echo __('Your Panel Name:') ?>" value="<?php echo $materialcode; ?>" class="form-control input-text" type="text" readonly data-validate="{required:true}"/>
            </div>
        </div>
     <?php if(!$materialcode): ?>
        <div class="container showdiv mb-4" style="display: none">
          <div class="row">
               <div class="col-md-12 col-lg-6">
                    <p><strong>Length (mm): </strong><span id="uncutlength"></span></p><p><strong>Width (mm): </strong><span id="uncutwidth"></span></p><p><strong>Thickness (mm): </strong><span id="uncutthickness"></span></p><p><strong>Price (Ex VAT): </strong><span id="uncutprice"></span></p>
                    <input type="hidden" id="clength" name="clength" value=""/>
                    <input type="hidden" id="cwidth" name="cwidth" value=""/>
                    <input type="hidden" id="cpaneldescription" name="cpaneldescription" value=""/>
               </div>
          </div>
        </div>
        <div class="container jumboomessage" style="display: none">
               <div class="row">
                    <div class="field required form-group col-md-12 col-lg-6 ">
                    <div class="d-flex align-items-center">
                         
                    <label class="mr-5 mb-0 greentext" for="">This board is available for cut to size panels</label>
                    </div>
                    </div>
               </div>
        </div>
        
        <div class="container uncut" style="display: none">
               <div class="row">
                    <div class="field required form-group col-md-12 col-lg-6 ">
                    <div class="d-flex align-items-center withoutcut">
                         
                    <label class="mr-5 mb-0" for="">Do you want to add a full board without cutting?</label>
                    
                    <div class="d-flex align-items-center">
                         <span class="d-flex align-items-center"><input id="uncutyes" required="" type="radio" class="required-entry mt-0" name="uncut" value="Yes" ><label for="uncutyes" class="mr-4">Yes</label></span>
                         <span class="d-flex align-items-center"><input id="uncutno" required="" type="radio" checked class="required-entry mt-0" name="uncut" value="No"><label for="uncutno" checked="checked" class="mr-4">No</label></span>
                    </div>
                    </div>
          
                    </div>
                    <div class="field required form-group col-md-12 col-lg-1 showdiv" style="display: none;padding-top: 5px; text-align: right">
                     <label for="thickness"><?php /* @escapeNotVerified */ echo __('Qty:') ?><span style="color: red;">
                         <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
                     </div>
                    <div class="field required form-group col-md-12 col-lg-1 showdiv" style="display: none;">
                         
                         <div class="control">
                        
                         <input name="cqty" id="cqty" title="<?php /* @escapeNotVerified */ echo __('Qty:') ?>" value="<?php echo $cqty; ?>" class="form-control input-text validate-greater-than-zero" data-validate="{required:true}" type="text"/>
                         </div>
                     </div>
                    <div class="field required form-group col-md-12 col-lg-4">
                    <button type="submit" style="background: #255792; float: left;display: none" class="btn btn-secondary pull-right"><span>Add To Quote</span></button>
          
                    </div>
               </div>
          </div>
        <?php endif; ?>
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for=""><?php /* @escapeNotVerified */ echo __('Length (mm):') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="length" id="length" title="<?php /* @escapeNotVerified */ echo __('Length (mm):') ?>" value="<?php echo $length; ?>" class="form-control input-text validate-number-range number-range-50-<?php echo $lengthval; ?>" type="text" data-validate="{required:true,'validate-number-range':true}" data-msg-validate-number-range="The value must be between 50 and <?php echo $lengthval; ?>"/>
               <div for="length" generated="true" class="mage-error" id="length-error-2" style="display: block;"></div>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for=""><?php /* @escapeNotVerified */ echo __('Width (mm):') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="width" id="width" title="<?php /* @escapeNotVerified */ echo __('Width (mm):') ?>" value="<?php echo $width; ?>" class="form-control input-text validate-number-range number-range-0-<?php echo $widthval; ?>" type="text" data-validate="{required:true,'validate-number-range':true}" data-msg-validate-number-range="The value must be less then and equals to <?php echo $widthval; ?>"/>
               <div for="width" generated="true" class="mage-error" id="width-error-2" style="display: block;"></div>
            </div>
        </div>
         
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for="thickness"><?php /* @escapeNotVerified */ echo __('Material Thickness (mm):') ?></label>
            <div class="control">
               <input name="thickness" id="thickness" readonly title="<?php /* @escapeNotVerified */ echo __('Material Thickness (mm):') ?>" value="<?php echo $thickness; ?>" class="form-control input-text validate-number-range number-range-0-999999999999" data-validate="{'validate-number-range':true}" type="text"/>
            </div>
        </div>
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for="price"><?php /* @escapeNotVerified */ echo __('Price per full board (Ex VAT):') ?></label>
            <div class="control price">
               <span id="price"><?php if($price){;echo $price; }; ?></span>
            </div>
        </div>
         
        
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for=""><?php /* @escapeNotVerified */ echo __('Part Description:') ?></label>
            <div class="control">
               <input name="paneldescription" id="paneldescription" title="<?php /* @escapeNotVerified */ echo __('Part Description:') ?>" maxlength="45" value="<?php echo $paneldescription; ?>" class="form-control input-text" type="text"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for="thickness"><?php /* @escapeNotVerified */ echo __('Qty:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="qty" id="qty" title="<?php /* @escapeNotVerified */ echo __('Qty:') ?>" value="<?php echo $qty; ?>" class="form-control input-text validate-greater-than-zero" data-validate="{required:true}" type="text"/>
            </div>
        </div>
        
         <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for="cabinetno"><?php /* @escapeNotVerified */ echo __('Cabinet No:') ?></label>
            <div class="control">
               <input name="cabinetno" id="cabinetno" title="<?php /* @escapeNotVerified */ echo __('Cabinet No') ?>" maxlength="40" value="<?php echo $cabinetno; ?>" class="form-control input-text" type="text"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6 hidediv">
            <label for="specialnotes"><?php /* @escapeNotVerified */ echo __('Special Notes/Extra Information:') ?></label>
            <div class="control">
               <input name="specialnotes" id="specialnotes" title="<?php /* @escapeNotVerified */ echo __('Special Notes/Extra Information:') ?>" value="<?php echo $specialnotes; ?>" class="form-control input-text" type="text" />
            </div>
        </div>
        
        </div>
        
     <div class="row mt-4 hidediv">
          <div class="field required form-group col-md-12 col-lg-6" >
               <h2 class="mt-4 mb-3">Edge Banding Option</h2>
               <span class="extraedgeoption">If your edging doesn't match your board please note in the field above and contact us</span>


               <div id="edgingbanding">
                    <label for="edgingbanding"><?php /* @escapeNotVerified */ echo __('Edge Banding:') ?></label>
                    <div class="control edgingbanding">
                         <span>
                       <input <?php if(strpos($edgingbanding, 'Edge Top') !== false){; echo 'checked=checked';}; ?> id="edgitop" type="checkbox" name="edgingbanding[]" value="Edge Top"><label for="edgitop">Edge Top</label></span>
                       <span>
                         <input <?php if(strpos($edgingbanding, 'Edge Bottom') !== false){; echo 'checked=checked';}; ?> id="edgibottom" type="checkbox" name="edgingbanding[]" value="Edge Bottom"><label for="edgibottom">Edge Bottom</label></span>
                       <span>
                         <input <?php if(strpos($edgingbanding, 'Edge Left') !== false){; echo 'checked=checked';}; ?> id="edgileft" type="checkbox" name="edgingbanding[]" value="Edge Left"><label for="edgileft">Edge Left</label></span>
                       <span>
                         <input <?php if(strpos($edgingbanding, 'Edge Right') !== false){; echo 'checked=checked';}; ?> id="edgiright" type="checkbox" name="edgingbanding[]" value="Edge Right"><label for="edgiright">Edge Right</label></span>
                    </div>
               </div>

               
               <div class="field required form-group mt-5" id="edgingoption" <?php if($edgingbanding == '' || $edgingbanding == 'No'){; echo 'style="display: none;"';}; ?>>
                    <label for="edgingbanding"><?php /* @escapeNotVerified */ echo __('Edging Options:') ?></label>
                    <div class="control edgingbanding" id="edgingfirst">
                         <?php
                              $edgearray = array();
                              if($edgetype != ''):
                              $edgearray = explode(',',$edgetype);
                              for($i=0;$i<count($edgearray);$i++){
                                   $edgeoption = $edgearray[$i]; 
                                   if($edgeoption==1){
                                        $label = '0.6mm MDF preparation tape';
                                   }else if($edgeoption==2){
                                        $label = '1mm Standard ABS matching';
                                   }else if($edgeoption==3){
                                        $label = '2mm Standard ABS matching';
                                   }else if($edgeoption==4){
                                        $label = '1mm Airtec Matching';
                                   }else if($edgeoption==5){
                                        $label = '2mm Airtec Matching';
                                   }else if($edgeoption==6){
                                        $label = '1mm Wood Veneer Matching';
                                   }else if($edgeoption==7){
                                        $label = '2mm Wood Veneer Matching';
                                   } ?>
                                   <span><input id="edgingfirst-<?php echo $edgeoption; ?>" type="checkbox" name="edgingbandingop" <?php if($edgeoption==$edgingbandingop){;echo 'checked="checked"';}; ?> class="checkbox required" onclick="edgingselect('<?php echo $edgeoption; ?>')" value="<?php echo $edgeoption; ?>" ><label for="edgingfirst-<?php echo $edgeoption; ?>"><?php echo $label; ?></label></span>
                                   
                         <?php     }
                         ?>
                         <?php endif; ?>
                    </div>
               </div>
               <div class="field required form-group mt-5" id="edgingprofile" <?php if($edgingbanding == '' || $edgingbanding == 'No'){; echo 'style="display: none;"';}; ?>>
               <label for="edgingbandingop"><?php /* @escapeNotVerified */ echo __('Radius:') ?></label>

                    <div class="control edgingbanding" id="edgingsecond">
                    <?php
                         $radiusarray = array();
                         if($radius != ''):
                         if($edgingbandingop==2 || $edgingbandingop==4 || $edgingbandingop==6){ ?>
                              <style>
                                   #spanedgingsecond-2{display: inline-block}
                                   #spanedgingsecond-3{display: none}
                              </style>
                    <?php     }elseif($edgingbandingop==3 || $edgingbandingop==5 || $edgingbandingop==7){ ?>
                              <style>
                                   #spanedgingsecond-2{display: none}
                                   #spanedgingsecond-3{display: inline-block}
                              </style>
                    <?php     }else{ ?>
                              <style>
                                   #spanedgingsecond-2{display: inline-block}
                                   #spanedgingsecond-3{display: inline-block}
                              </style>
                    <?php     }
                         $radiusarray = explode(',',$radius);
                         for($i=0;$i<count($radiusarray);$i++){
                              $radiusoption = $radiusarray[$i];                                    
                                   if($radiusoption==1){
                                      $slabel = 'Square';
                                   }else if($radiusoption==2){
                                        $slabel = '1mm Radius';
                                   }else if($radiusoption==3){
                                        $slabel = '2mm Radius';
                                   } ?>
                                   <span id="spanedgingsecond-<?php echo $radiusoption; ?>"><input <?php if($radiusoption==$edgingbandingpro){;echo 'checked="checked"';}; ?> id="edgingsecond-<?php echo $radiusoption; ?>" type="checkbox" name="edgingprofile" onclick="radiusselect('<?php echo $radiusoption; ?>')" value="<?php echo $radiusoption; ?>" class="checkbox required" ><label for="edgingsecond-<?php echo $radiusoption; ?>"><?php echo $slabel; ?></label></span>
                    <?php }
                    endif; ?>
                    </div> 
               </div>
          </div>
          <div class="field required form-group col-md-12 col-lg-4 text-center hidediv" id="edgingbandingimg">
               
                    <img src="<?php echo $this->getViewFileUrl('images/pp-edgebanding.jpg'); ?>">
               
               <a target="_blank" href="<?php echo $this->getUrl('edgebanding'); ?>"><strong>Click here for an explanation of our edgebanding options</strong></a>
          </div>
               
          
          <div class="field required form-group bottomcuttingbox col-md-12 hidediv">
               <h2 class="mt-4 mb-3"><?php /* @escapeNotVerified */ echo __('Grain Matching:') ?></h2>
            <div class="control edgingbanding">
          <span>
              <!--<input <?php if($grainmatiching == 'Yes'){; echo 'checked=checked';}; ?> id="grainmatching" name="grainmatching" type="checkbox" value="Yes"><label for="grainmatching"><?php /* @escapeNotVerified */ echo __('Grain Matching:') ?></label></span>-->
              <p>If you have multiple parts with matiching grain - for example a stack of drawer fronts or a pair of doors - please note the individual parts and note the request on your order.</p>
            </div>
          </div>
          
          <div class="field contact_name required form-group col-md-12 hidediv">
               <label for="contact_name"><?php /* @escapeNotVerified */ echo __('Upload Dxf File:') ?></label>
               <a tabindex="0" class="popovericon ml-5" role="button" data-toggle="popover" data-trigger="focus" title="" data-content="if you have a simple drilling file for hinge holes or line bores please download it here... if you have more complex shaped panels that require nested routing, or 3D shapes and 5-axis CNC operations please call us to discuss, we are happy to provide a quote for the service" data-original-title=""><i class="fas fa-info-circle"></i></a>
               <div class="control">
                   <input id="panel_image" name="image" data-ui-id="adminhtml-panel-edit-tab-main-0-fieldset-element-file-image" value="" title="Image" type="file" class="input-file">
                   
                   
                   <?php if($image){ ?>
                   <input type="hidden" name="image" value="<?php echo $image; ?>">
                   <a target="blank" href="<?php echo $this->getUrl('pub/media').$image; ?>" title="<?php echo str_replace('panel/','',$image); ?>" download="<?php echo str_replace('panel/','',$image); ?>">Download</a>
                   <?php } ?>
                  <p><i>Note: If any of your parts require a shaped CNC trim or drilling please supply a file here and call us to discuss, an additional charge for shaped and drilled panels applies</i></p> 
                   
               </div>
          </div>
</div>

        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
      <div class="secondary hidediv">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Save') ?>" class="btn form-btn">
              <?php /* @escapeNotVerified */ echo __('Save') ?>
            </button>
     </div>
     <?php if(isset($_SERVER['HTTP_REFERER'])){ ?>
          <div class="secondary form-btn-set ml-3"><a class="btn btn-outline-secondary" href="<?php echo $_SERVER['HTTP_REFERER']; ?>" title="Go back">Go Back</a></div>
     <?php } ?>
     </div>
</form>
<?php endif; ?>
<?php endif; ?>
</div>
</div>
</div>
</div>
</div>


<!-- Modal -->
<div class="modal fade" id="productpopup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Select Material From Here</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
           <div class="container">
               <div class="row">
               <div class="col-md-12">
                    <div class="searchproduct mb-5">
                         <input onkeyup="searchproduct();" type="text" id="searchquerychange" placeholder="Search Material" />
                    </div>
               </div>
               </div>
          </div>
        <div class="container">
          
          <div class="row" id="storealldefalut">
              
               <div class="col-md-12 col-lg-3">
                    <div class="form-group">
                         <label>Board Type</label>
                         <select onchange="searchproduct();" id="boardtypechange">
                               <?php                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'board_type');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>
                    
                    <div class="form-group">
                         <label>Manufacturer</label>
                         <select onchange="searchproduct();" id="manufacturerchange">
                              <?php                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'manufacturer');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>
                    
                    <div class="form-group">
                         <label>Thickness</label>
                         <select onchange="searchproduct();" id="thicknesschange">
                              <?php
                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'thickness');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>  
               </div>
               <div class="col-md-12 col-lg-9">
                    <div class="product-listing" id="product-listing">
                         <div class="container">
                              <div class="row">
                                   <?php if(count($productslimit)>0){
                                        $imageHelper  = $om->get('\Magento\Catalog\Helper\Image');?>
                                   <?php foreach($productslimit as $product){
                                        $imageUrl = $imageHelper->init($product, 'product_page_image_medium')
                            ->constrainOnly(FALSE)
                            ->keepAspectRatio(TRUE)
                            ->keepFrame(FALSE)
                            ->resize(200, 200)
                            ->getUrl();
                            if (strpos($imageUrl, 'placeholder') !== false) {
                            $imageUrl = $this->getViewFileUrl('images/image.jpg');
                            }?>
                                   <div class="col-md-6 col-lg-4 mb-5">
                                        <div class="proimage">
                                             <img src="<?php echo $imageUrl; ?>" alt="<?php echo $product->getName(); ?>" />
                                        </div>
                                       <span class="proname"><?php echo substr($product->getName(),0,50); ?></span>
                                       <button class="btn btn-secondary" onclick="addtocutlist(<?php echo $product->getId(); ?>);"><span>Add to Cutlist</span></button>
                                   </div>
                                   <?php }} ?>
                              </div>
                         </div>
                    </div>
                    
               </div>
          
        </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="closebtn" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<style>
     table > thead > tr > th, table > tbody > tr > th, table > tfoot > tr > th, table > thead > tr > td, table > tbody > tr > td, table > tfoot > tr > td{padding: 8px 7px;}
     #edgingbanding span, #edgingsecond span, #edgingfirst span{margin-right: 15px}
     .my-address-form{font-size:13px;}
     .pull-right{float: right;}
     #edgingbandingimg img{width: 100%;}
     #edgingbandingimg a{display: block;}
     .popover-body { font-size: 14px; }
     .popovericon{font-size: 24px}
     #productpopup select option{font-size: 14px;}
     .my-address-form{padding: 15px;}
     .proimage{ height: 240px; display: flex; background: #f3f3f3; margin: 0 0 8px; align-items: center;}
     .control.price{font-size: 16px; margin-top: 7px;}
     .withoutcut { padding: 10px 15px; background:#01cb81; border: 1px solid #00915c;}
     .container.showdiv{font-size: 16px;}
     .container.showdiv p{width: 50%; display: inline-block;}
     .table-responsive caption{border: 1px solid #000000; padding: 10px; height: auto; position: absolute; 
width: auto; text-align: center; position: inherit; font-size: 16px; color: #000; margin: 0; background: #008be2; caption-side:top; font-weight: bold;}
.jumboomessage .align-items-center { padding: 10px 15px; background: #008be2; border: 1px solid #00915c; }
.jumboomessage .align-items-center label{color: #FFFF00 !important;}
</style>



<script type="text/javascript">
require([
    'jquery'
], function ($) {
$(document).ready(function(){
     $('#material').change(function(){
     $('#edgingfirst').html('');
     $('#edgingsecond').html('');
        var reviewUrl = '<?php echo $block->getBaseUrl(); ?>product.php';
        var proid = $(this).children("option:selected").val();
            $.ajax(reviewUrl, 
          {
              dataType: 'json', // type of response data
             // timeout: 500,     // timeout milliseconds
              data: { pro_id: proid },
              success: function (msg) {   // success callback function
               //document.getElementById("materialcode").value = msg.code;
               //document.getElementById("price").innerHTML = msg.price;               
               //document.getElementById("thickness").value = msg.thickness;
               //uncut start
               $('#edgingbanding input').prop('checked', false);
               $('#materialcode').val(msg.code);
               $('#price').html(msg.price);
               $('#thickness').val(msg.thickness);
               $('#pricefull').val(msg.price);
               $('#uncutwidth').text('');
               $('#uncutlenght').text('');
               $('#uncutthickness').text('');
               $('#uncutprice').text('');
               $('#uncutwidth').text(msg.width);
               $('#uncutlength').text(msg.length);
               $('#clength').val(msg.length);
               $('#cwidth').val(msg.width);
               $('#cpaneldescription').val(msg.paneldescription);               
               $('#uncutthickness').text(msg.thickness);
               $('#uncutprice').text(msg.price);
               if(parseInt(msg.width)===2070 && parseInt(msg.length)===2800){
                    $('.container.uncut').hide();
                    $('.container.jumboomessage').show();
               }else{
                    $('.container.uncut').show();
                    $('.container.jumboomessage').hide();
               }
               //uncut end
               var totalwidth = msg.width;
               totalwidth = parseInt(totalwidth)-30;
               var totallength = msg.length;
               totallength = parseInt(totallength)-30;
               $('#width').val('');
               $('#width').attr('class','');
               $('#width').attr('data-msg-validate-number-range','');
               $('#width').addClass('form-control');
               $('#width').addClass('input-text');
               $('#width').addClass('validate-number-range number-range-0-'+totalwidth);
               $('#width').attr('data-msg-validate-number-range','The value must be less than or equals to '+totalwidth);
               $('#width-error').hide();
               $('#width-error-2').html('The value must be less than or equals to '+totalwidth);
               
               $('#length').val('');
               $('#length').attr('class','');
               $('#length').attr('data-msg-validate-number-range','');
               $('#length').addClass('form-control');
               $('#length').addClass('input-text');
               $('#length').addClass('validate-number-range number-range-50-'+totallength);
               $('#length').attr('data-msg-validate-number-range','The value must be between 50 and '+totallength);
               $('#length-error').hide();
               $('#length-error-2').html('The value must be between 50 and '+totallength);
               //document.getElementById("sku").value = msg.sku;
               //document.getElementById("proid").value = msg.proid;
               jQuery('#sku').val(msg.sku);
               jQuery('#proid').val(msg.proid);
               jQuery('#material').val(msg.proid);
               
               //code start for validation

               if(parseInt(msg.thickness)<8){
                    $('#edgingfirst').html('<b>The minimum thickness of panel that we can edgeband is 8mm<b>');
                     $('#edgingbanding').hide();
                     $('#edgingoption').show();
                     $('#edgingprofile').hide();
                     
               }else{
                    $('#edgingbanding').show();
                    $('#edgingprofile').hide();
                    var firstedge = msg.edgetype;
                    var secondedge =msg.radius;
                    firstedge = firstedge.split(',');
                    secondedge = secondedge.split(',');
                    var i;
                    var html;
                    var label;
                    var value;
                    for (i = 0; i < firstedge.length; ++i) {
                         value = firstedge[i];
                         if(value==1){
                            label = '0.6mm MDF preparation tape';
                         }else if(value==2){
                              label = '1mm Standard ABS matching';
                         }else if(value==3){
                              label = '2mm Standard ABS matching';
                         }else if(value==4){
                              label = '1mm Airtec Matching';
                         }else if(value==5){
                              label = '2mm Airtec Matching';
                         }else if(value==6){
                              label = '1mm Wood Veneer Matching';
                         }else if(value==7){
                              label = '2mm Wood Veneer Matching';
                         }
                         
                         html = '<span><input id="edgingfirst-'+value+'" type="checkbox" name="edgingbandingop" class="checkbox required" onclick="edgingselect('+value+')" value="'+value+'" ><label for="edgingfirst-'+value+'">'+label+'</label></span>';
                         
                         
                         if(value==1001){
                              //$('#edgingfirst').append('');
                              $('#edgingfirst').append('<b>No edgeband option available for this product</b>');
                              $('#edgingbanding').hide();
                              $('#edgingoption').show();
                              $('#edgingprofile').hide();
                         }else if(value){
                              $('#edgingfirst').append(html);
                              $('#edgingbanding').show();
                              $('#edgingoption').hide();

                         }
                    }
                    
                    
                    
                    var j;
                    var shtml;
                    var slabel;
                    var svalue;
                    for (j = 0; j < secondedge.length; ++j) {
                         svalue = secondedge[j];
                         if(svalue==1){
                            slabel = 'Square';
                         }else if(svalue==2){
                              slabel = '1mm Radius';
                         }else if(svalue==3){
                              slabel = '2mm Radius';
                         }
                         
                         shtml = '<span id="spanedgingsecond-'+svalue+'"><input id="edgingsecond-'+svalue+'" type="checkbox" name="edgingprofile" onclick="radiusselect('+svalue+')" value="'+svalue+'" class="checkbox required" ><label for="edgingsecond-'+svalue+'">'+slabel+'</label></span>';
                         $('#edgingsecond').append(shtml);
                    }
               }
               //document.getElementById("materialcode").innerHTML = $('#materialcode').append(msg.code);
               /*1-0.6mm MDF preparation tape
               2-1mm Standard ABS matching
               3-2mm Standard ABS matching
               4-1mm Airtec Matching
               5-2mm Airtec Matching
               6-1mm Wood Veneer Matching
               7-2mm Wood Veneer Matching
               1001 - No*/


              }
          });
     });
     
     $(".container.uncut input[name='uncut']").click(function(){
          var uncutval = $(this).val();
          var action = $("#cutlist_form").attr('action');
          var newaction = action;
          if (uncutval === 'Yes'){
               $(".container.uncut .btn.btn-secondary").show();
               $(".hidediv").hide();
               $(".showdiv").show();               
               newaction = action.replace("cutting", "uncut");
               $("#cutlist_form").attr('action',newaction);

               
          }else{
               $(".container.uncut .btn.btn-secondary").hide();
               $(".hidediv").show();
               $(".showdiv").hide();
               newaction = action.replace("uncut", "cutting");
               $("#cutlist_form").attr('action',newaction);
          }
     });
     
     
     $('#edgingbanding input').change(function(){
          
          if(this.checked){
               $('#edgingoption').css('display', 'block');
               
          }else{
                    var favorite = [];
                    $.each($("input[name='edgingbanding[]']:checked"), function(){
                         favorite.push($(this).val());
                    });
                    if(favorite.length !== 0){
                    }else{
                         $('#edgingoption input').prop('checked', false);
                         $('#edgingprofile input').prop('checked', false);
                         $('#edgingoption').css('display', 'none');
                         $('#edgingprofile').css('display', 'none');
                    }
          }     
     });
     });

});


//search on popupfunction
     function searchproduct(){
         var searchquery = jQuery('#searchquerychange').val();
         var boarddata = jQuery('#boardtypechange').val();
         var proid = jQuery('#pronamechange').val();
         var manufacturer = jQuery('#manufacturerchange').val();
         var color = jQuery('#colorchange').val();
         var thickness = jQuery('#thicknesschange').val();
         var length = jQuery('#lengthchange').val();
         var width = jQuery('#widthchange').val();
         //alert(searchquery+boarddata+proid+manufacturer+color+thickness);
         document.getElementById("storealldefalut").innerHTML='<img style="margin-left:20%;margin-top:20%;" src="<?php echo $this->getViewFileUrl('images/loader-2.gif'); ?>" />'
	     jQuery.ajax({
		method: "POST",
		url: "<?php echo $block->getBaseUrl(); ?>pro_search.php",
		data: { searchquery:searchquery,boarddata:boarddata,proid:proid,manufacturer:manufacturer,color:color,thickness: thickness,length:length,width:width}
		})
		.done(function( msgop ) {
		//alert(str);
               document.getElementById("storealldefalut").innerHTML= msgop;
		});
     }
     
     
     function clearfilter(){
         jQuery('#searchquerychange').val('');
         //alert(searchquery+boarddata+proid+manufacturer+color+thickness);
         document.getElementById("storealldefalut").innerHTML='<img style="margin-left:20%;margin-top:20%;" src="<?php echo $this->getViewFileUrl('images/loader-2.gif'); ?>" />'
	     jQuery.ajax({
		method: "POST",
		url: "<?php echo $block->getBaseUrl(); ?>pro_search.php",
		data: { searchquery:'',boarddata:'',proid:'',manufacturer:'',color:'',thickness: '',length:'',width:''}
		})
		.done(function( msgop ) {
		//alert(str);
               document.getElementById("storealldefalut").innerHTML= msgop;
               document.getElementById("clearfilter").innerHTML= '';
               document.getElementById("searchquerychange").value= '';
               
		});
     }

// function after clicking add to cutlist button
     function addtocutlist(proid){
          
          var reviewUrl = '<?php echo $block->getBaseUrl(); ?>product.php';
          jQuery.ajax(reviewUrl, 
          {
              dataType: 'json', // type of response data
             // timeout: 500,     // timeout milliseconds
              data: { pro_id: proid },
              success: function (msg) {   // success callback function
               //console.log(msg);
               //document.getElementById("materialcode").value = msg.code;
              // document.getElementById("price").innerHTML = msg.price;
               jQuery('#pricefull').val(msg.price);
               //document.getElementById("thickness").value = msg.thickness;
               jQuery('#edgingbanding input').prop('checked', false);
               
               jQuery('#materialcode').val(msg.code);
               jQuery('#price').html(msg.price);
               jQuery('#thickness').val(msg.thickness);
               //uncut start
               jQuery('#uncutwidth').text('');
               jQuery('#uncutlenght').text('');
               jQuery('#uncutthickness').text('');
               jQuery('#uncutprice').text('');
               jQuery('#uncutwidth').text(msg.width);
               jQuery('#uncutlength').text(msg.length);
               jQuery('#uncutthickness').text(msg.thickness);
               jQuery('#uncutprice').text(msg.price);
               jQuery('#clength').val(msg.length);
               jQuery('#cwidth').val(msg.width);
               jQuery('#cpaneldescription').val(msg.paneldescription);
               if(parseInt(msg.width)===2070 && parseInt(msg.length)===2800){
                    jQuery('.container.uncut').hide();
                    jQuery('.container.jumboomessage').show();
               }else{
                    jQuery('.container.uncut').show();
                    jQuery('.container.jumboomessage').hide();
               }
               //uncut end
               var totalwidth = msg.width;
               totalwidth = parseInt(totalwidth)-30;
               var totallength = msg.length;
               totallength = parseInt(totallength)-30;             
               jQuery('#width').val('');
               jQuery('#width').attr('class','');
               jQuery('#width').attr('data-msg-validate-number-range','');
               jQuery('#width').addClass('form-control');
               jQuery('#width').addClass('input-text');
               jQuery('#width').addClass('validate-number-range number-range-0-'+totalwidth);
               jQuery('#width').attr('data-msg-validate-number-range','The value must be less than or equals to '+totalwidth);
               jQuery('#width-error').hide();
               jQuery('#width-error-2').html('The value must be less than or equals to '+totalwidth);
               
               jQuery('#length').val('');
               jQuery('#length').attr('class','');
               jQuery('#length').attr('data-msg-validate-number-range','');
               jQuery('#length').addClass('form-control');
               jQuery('#length').addClass('input-text');
               jQuery('#length').addClass('validate-number-range number-range-50-'+totallength);
               jQuery('#length').attr('data-msg-validate-number-range','The value must be between 50 and '+totallength);
               jQuery('#length-error').hide();
               jQuery('#length-error-2').html('The value must be between 50 and '+totallength);
               jQuery('#sku').val(msg.sku);
               jQuery('#proid').val(msg.proid);
               jQuery('#material').val(msg.proid);
               //document.getElementById("sku").value = msg.sku;
               //document.getElementById("proid").value = msg.proid;
               //document.getElementById("material").value = msg.proid;
               
               //code start for validation
               jQuery('#edgingfirst').html('');
               jQuery('#edgingsecond').html('');
               if(parseInt(msg.thickness)<8){
                    jQuery('#edgingfirst').html('<b>The minimum thickness of panel that we can edgeband is 8mm<b>');
                     jQuery('#edgingbanding').hide();
                     jQuery('#edgingoption').show();
                     jQuery('#edgingprofile').hide();
                     
               }else{
                    jQuery('#edgingbanding').show();
                    jQuery('#edgingprofile').hide();
                    var firstedge = msg.edgetype;
                    var secondedge =msg.radius;
                    firstedge = firstedge.split(',');
                    secondedge = secondedge.split(',');
                    var i;
                    var html;
                    var label;
                    var value;
                    for (i = 0; i < firstedge.length; ++i) {
                         value = firstedge[i];
                         if(value==1){
                            label = '0.6mm MDF preparation tape';
                         }else if(value==2){
                              label = '1mm Standard ABS matching';
                         }else if(value==3){
                              label = '2mm Standard ABS matching';
                         }else if(value==4){
                              label = '1mm Airtec Matching';
                         }else if(value==5){
                              label = '2mm Airtec Matching';
                         }else if(value==6){
                              label = '1mm Wood Veneer Matching';
                         }else if(value==7){
                              label = '2mm Wood Veneer Matching';
                         }
          
                         html = '<span><input id="edgingfirst-'+value+'" type="checkbox" name="edgingbandingop" class="checkbox required" onclick="edgingselect('+value+')" value="'+value+'" ><label for="edgingfirst-'+value+'">'+label+'</label></span>';
                         
                         
                         if(value==1001){
                              //$('#edgingfirst').append('');
                              jQuery('#edgingfirst').append('<b>No edgeband option available for this product</b>');
                              jQuery('#edgingbanding').hide();
                              jQuery('#edgingoption').show();
                              jQuery('#edgingprofile').hide();
                         }else if(value){
                              jQuery('#edgingfirst').append(html);
                              jQuery('#edgingbanding').show();
                         }
                    }
                    
                    
                    
                    var j;
                    var shtml;
                    var slabel;
                    var svalue;
                    for (j = 0; j < secondedge.length; ++j) {
                         svalue = secondedge[j];
                         if(svalue==1){
                            slabel = 'Square';
                         }else if(svalue==2){
                              slabel = '1mm Radius';
                         }else if(svalue==3){
                              slabel = '2mm Radius';
                         }
                         
                         shtml = '<span id="spanedgingsecond-'+svalue+'"><input id="edgingsecond-'+svalue+'" type="checkbox" name="edgingprofile" onclick="radiusselect('+svalue+')" value="'+svalue+'" class="checkbox required" ><label for="edgingsecond-'+svalue+'">'+slabel+'</label></span>';
                         jQuery('#edgingsecond').append(shtml);
                    }
               }
               
               //document.getElementById("tproductcode").innerHTML = msg.sku;
               //document.getElementById("tmaterial").innerHTML = msg.code;
               //document.getElementById("tlength").innerHTML = msg.length;
               //document.getElementById("twidth").innerHTML = msg.width;
               //document.getElementById("tpaneldescription").innerHTML = msg.paneldescription;
               document.getElementById("closebtn").click();

              }
          });
          
          
     }
     
     function edgingselect(id){
          jQuery('#edgingsecond input').prop('checked', false);
          var oldvalue = jQuery('#edgingfirst input:checked').val();
          if(oldvalue === undefined){
               jQuery('#edgingfirst input').prop('checked', false);
               jQuery('#edgingprofile').css('display', 'none');
          }else{
               jQuery('#edgingfirst input').prop('checked', false);
               jQuery('#edgingfirst-'+id).prop('checked', true);
               jQuery('#edgingprofile').css('display', 'block');
          }
          if(id==2 || id==4 || id==6){
               jQuery('#spanedgingsecond-2').show();
               jQuery('#spanedgingsecond-3').hide();
          }else if(id==3 || id==5 || id==7){
               jQuery('#spanedgingsecond-2').hide();
               jQuery('#spanedgingsecond-3').show();
          }else{
               jQuery('#spanedgingsecond-2').show();
               jQuery('#spanedgingsecond-3').show();
          }
     }
     
     function radiusselect(id){
          var soldvalue = jQuery('#edgingsecond input:checked').val();
          if(soldvalue === undefined){
               jQuery('#edgingsecond input').prop('checked', false);
          }else{
               jQuery('#edgingsecond input').prop('checked', false);
               jQuery('#edgingsecond-'+id).prop('checked', true);
          }
     }
     
     
     function cuttinglist(cuttingid){
		document.getElementById("cuttinglistdata").innerHTML='<img style="margin-left:20%;margin-top:20%;" src="<?php echo $this->getViewFileUrl('images/loader-2.gif'); ?>" />'
	        jQuery.ajax({
		method: "POST",
		url: "<?php echo $block->getBaseUrl(); ?>cutlistdata.php",
		data: { cuttingid:cuttingid}
		})
		.done(function( msgop ) {
		//alert(str);
               document.getElementById("cuttinglistdata").innerHTML= msgop;
		});
	}

</script>
<script>
    require([
        'jquery',
        'bootstrap'
    ], function($){
        $(function () {
            $('[data-toggle="popover"]').popover({                
            container: 'body',
            delay: 100,
            placement: 'right',
            trigger: 'hover'
            });
        });
    });
</script>

<div class="modal fade" id="cutlistpopup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">View Cutting List</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
               <div class="col-md-12" id="cuttinglistdata">
			   </div>
		  </div>
		</div>
	  </div>
	</div>
  </div>
</div>

<?php
    $session = $om->get('Magento\Customer\Model\Session');
    $productsession = $session->getProductsession();    
?>

<script>
     require(['jquery'], function ($) {
          $(window).load(function () {
           $('#showleftnav').trigger('click');
           <?php if($productsession){ ?>
           
           //$('#material option[value="<?php echo $productsession; ?>"]').attr("selected", "selected");
           //$('#material').val('<?php echo $productsession; ?>');
           $('#material option[value=<?php echo $productsession; ?>]').prop('selected', 'selected').change();
          <?php } ?>
          });
          $(".deliverysection input[name='delivery']").click(function(){
          var deliveryval = $(this).val();
               if(deliveryval ==='delivery'){
                    $('#postcode').show();
                    $('#postcode').prop('required',true);
               }else{
                    $('#postcode').prop('required',false);
                    $('#postcode').hide();
                    $('#postcode').val('');
               }
          });
          
          $('#postcode').keyup(function () {
          $(this).val(function (_, val) {
              return val.toUpperCase();
          });
          });
     });
</script>
<?php $session->unsProductsession(); ?>