<?php
    
     $om = \Magento\Framework\App\ObjectManager::getInstance();
     $eavConfig = $om->get('\Magento\Eav\Model\Config');
     $customerSession = $om->create('Magento\Customer\Model\Session');
     if($customerSession->isLoggedIn()) {
         $cusid =  $customerSession->getCustomer()->getId();
     }else{
         $cusid= 0;
     }
     $helper = $this->helper('pws\panel\Helper\Data');
     $values = $helper->getGroupListById($cusid);
     $cuttingid = $this->getRequest()->getParam('id');
     $productslimit = $block->getProductCollection();
     $products =$block->getProductCollectionAll();
     
     $created = $om->create('Pws\Panel\Model\Cutlist')->load($cuttingid);
     $panelid = $created->getPanelId();
     

     
     
?>

<div class="blue-title-sec">
    <div class="container">              
        <div class="row align-items-center my-address-row">
          <div class="col-md-12 col-lg-4">
            <h2 class="mb-0"><?= $block->escapeHtml(__('Edit Cutting List')) ?></h2>
          </div>
          <div class="col-md-12 col-lg-8">
          <p class="mb-0"><?= $block->escapeHtml(__('Please fill the form below for the Cutting List')) ?></p>
          </div>
        </div>           
    </div>
</div>
<div class="main-content-sec grey-bg-sec">

<div class="container">
<div class="row justify-content-center">       
<div class="col-md-12 col-lg-12"> 
<div class="my-address-form">
     <div class="table-responsive">
          <table class="cutlist-table">
               <thead>
                    <!--<th>S. No.</th>-->
                    <th>Part Description</th>
                    <th>Material</th>
                    <th>Product Code</th>
                    <th>Grain</th>
                    <th>Length (mm)</th>
                    <th>Width (mm)</th>
                    <!--<th>Qty</th>
                    <th>Edging Top</th>
                    <th>Edging Bottom</th>
                    <th>Edging Left</th>
                    <th>Edging Right</th>
                    <th>Cabinet No.</th>
                    <th>Actions</th>-->
               </thead>
               <tbody>
                    <tr>
                         <!--<td id="tsno">1.</td>-->
                         <td id="tpaneldescription"><?php echo $created->getPaneldescription(); ?></td>
                         <td id="tmaterial"><?php echo $created->getMaterial(); ?></td>
                         <td id="tproductcode"><?php echo $created->getSku(); ?></td>
                         <td id="tgrain"><?php echo $created->getGrainmatching(); ?></td>
                         <td id="tlength"><?php echo $created->getLength(); ?></td>
                         <td id="twidth"><?php echo $created->getWidth(); ?></td>
                         <!--<td id="tqty"><?php echo $created->getQty(); ?></td>
                         <td id="tedgingtop"></td>
                         <td id="tedgingbottom"></td>
                         <td id="tedgingleft"></td>
                         <td id="tedgingright"></td>
                         <td id="tcabinetno"></td>
                         <td id="tActions"></td>-->
                    </tr>
               </tbody>
          </table>
          <div class="">
               <form class="form"
                    action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
                    id="cutlist_form_quote"
                    enctype="multipart/form-data"
                    method="post">
                    <input type="hidden" name="cutline_id" value="<?php echo $created->getCutlineId(); ?>" />
                    <input type="hidden" name="quotestatus" value="Request Sent" />
                    <button class="btn btn-secondary"><span>Submit For Quote</span></button>
                    
               </form>
          </div>
     </div>
</div>
</div>
</div>
</div>
     
<div class="container">
<div class="row justify-content-center">       
<div class="col-md-12 col-lg-12"> 
<div class="my-address-form">
          
     
<form class="form"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="cutlist_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
      <input type="hidden" name="cutline_id" value="<?php echo $created->getCutlineId(); ?>" />
      <input type="hidden" name="status" value="Created" />
     <input type="hidden" name="url_key" value="<?php echo $cusid; ?>" />
     <input type="hidden" name="panel_id" value="<?php echo $panelid; ?>" />
     <input type="hidden" id="sku" name="sku" value="<?php echo $created->getSku(); ?>" />
     <input type="hidden" name="qty" value="1" />
     <input type="hidden" name="proid" id="proid" value="<?php echo $created->getProid(); ?>" />
     <fieldset class="fieldset" style="margin-bottom: 20px;">
        <a class="btn btn-secondary mb-4" href="#productpopup" data-toggle="modal">For Material Code Please select Product Here</a>
     
        <div class="row">        
        <div class="field required form-group col-md-12">
            <label for="panel_image"><?php /* @escapeNotVerified */ echo __('Material:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <select id="material" name="material">
                    <option>--Please select a Material First--</option>
                   <?php if(count($products)>0){ ?>
                   <?php foreach($products as $product){
                         $productid = $product->getId();
                    
                    ?>
                   <option <?php if($created->getProid() == $productid){; echo 'selected="selected"'; }; ?> value="<?php echo $productid; ?>"><?php echo $product->getName(); ?></option>
                   <?php } ?>
                   <?php } ?>
                </select>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="materialcode"><?php /* @escapeNotVerified */ echo __('Material Code:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control" >
               <input id="materialcode" name="materialcode" title="<?php /* @escapeNotVerified */ echo __('Your Panel Name:') ?>" value="<?php echo $created->getMaterialcode(); ?>" class="form-control input-text" type="text" readonly data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for=""><?php /* @escapeNotVerified */ echo __('Length (mm):') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="length" id="length" title="<?php /* @escapeNotVerified */ echo __('Length (mm):') ?>" value="<?php echo $created->getLength(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for=""><?php /* @escapeNotVerified */ echo __('Width (mm):') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="width" id="width" title="<?php /* @escapeNotVerified */ echo __('Width (mm):') ?>" value="<?php echo $created->getWidth(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for=""><?php /* @escapeNotVerified */ echo __('Panel Description:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="paneldescription" id="paneldescription" title="<?php /* @escapeNotVerified */ echo __('Panel Description:') ?>" maxlength="230" value="<?php echo $created->getPaneldescription(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="thickness"><?php /* @escapeNotVerified */ echo __('Material Thickness (mm):') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="thickness" id="thickness" title="<?php /* @escapeNotVerified */ echo __('Material Thickness (mm):') ?>" value="<?php echo $created->getThickness(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field required form-group col-md-12 col-lg-6">
            <label for="specialnotes"><?php /* @escapeNotVerified */ echo __('Special Notes/Extra Information:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="specialnotes" id="specialnotes" title="<?php /* @escapeNotVerified */ echo __('Special Notes/Extra Information:') ?>" value="<?php echo $created->getSpecialnotes(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        </div>
        
        
        
        <h2 class="mt-4 mb-3">Edge Banding Option</h2>
        <span class="extraedgeoption">If your edging doesn't match your board please note in the field above and contact us</span>
     <div class="row mt-4">
          <div class="field required form-group col-md-12 col-lg-6">
            <label for="mmfstandardabs"><?php /* @escapeNotVerified */ echo __('1mm Standard ABS matching:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="mmfstandardabs" id="mmfstandardabs" title="<?php /* @escapeNotVerified */ echo __('1mm Standard ABS matching:') ?>" value="<?php echo $created->getMmfstandardabs(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
          </div>
          
          <div class="field required form-group col-md-12 col-lg-6">
            <label for="mmtstandardabs"><?php /* @escapeNotVerified */ echo __('2mm Standard ABS matching:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="mmtstandardabs" id="mmtstandardabs" title="<?php /* @escapeNotVerified */ echo __('2mm Standard ABS matching:') ?>" value="<?php echo $created->getMmtstandardabs(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
          
          <div class="field required form-group col-md-12 col-lg-6">
            <label for="mdfpreparation"><?php /* @escapeNotVerified */ echo __('0.6mm MDF preparation tape:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="mdfpreparation" id="mdfpreparation" title="<?php /* @escapeNotVerified */ echo __('0.6mm MDF preparation tape:') ?>" value="<?php echo $created->getMdfpreparation(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
          
          <div class="field required form-group col-md-12 col-lg-6">
            <label for="mmfairtec"><?php /* @escapeNotVerified */ echo __('1mm Airtec Matching:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="mmfairtec" id="mmfairtec" title="<?php /* @escapeNotVerified */ echo __('1mm Airtec Matching:') ?>" value="<?php echo $created->getMmfairtec(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
          
          <div class="field required form-group col-md-12 col-lg-6">
            <label for="mmtairtec"><?php /* @escapeNotVerified */ echo __('2mm Airtec Matching:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
               <input name="mmtairtec" id="mmtairtec" title="<?php /* @escapeNotVerified */ echo __('2mm Airtec Matching:') ?>" value="<?php echo $created->getMmtairtec(); ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
          
          
          <div class="field required form-group col-md-12 col-lg-6">
            <label for="edgingprofile"><?php /* @escapeNotVerified */ echo __('Edging Profile:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
              <select name="edgingprofile">
               <option <?php if($created->getEdgingprofile() == 'Square'){; echo 'selected="selected"';};?> value="Square">Square</option>
               <option <?php if($created->getEdgingprofile() == 'Redius'){; echo 'selected="selected"';};?> value="Redius">Redius</option>
              </select>
            </div>
        </div>
          
          <div class="field required form-group col-md-12 bottomcuttingbox">
            <div class="control">
              <input id="grainmatching" name="grainmatching" <?php if($created->getGrainmatching() == 'Yes'){; echo 'checked="checked"';};?> type="checkbox" value="Yes"><label for="grainmatching"><?php /* @escapeNotVerified */ echo __('Grain Matching:') ?></label>
              <p>If you have multiple parts with matiching grain - for example a stack of drawer fronts or a pair of doors - please note the individual parts and note the request on your order.</p>
            </div>
        </div>
          
         
     </div>
        
        
    
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
      <div class="secondary">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn form-btn">
              <?php /* @escapeNotVerified */ echo __('Submit') ?>
            </button>
     </div>
      <?php if(isset($_SERVER['HTTP_REFERER'])){ ?>
<div class="secondary form-btn-set ml-3"><a class="btn btn-outline-secondary" href="<?php echo $_SERVER['HTTP_REFERER']; ?>" title="Go back">Go Back</a></div>
<?php } ?>
     </div>
</form>
</div>
</div>
</div>
</div>
</div>


<!-- Modal -->
<div class="modal fade" id="productpopup" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title" id="exampleModalLabel">Select Material From Here</h2>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class="row">
               <div class="col-md-12">
                    <div class="searchproduct mb-5">
                         <input onkeyup="searchproduct();" type="text" id="searchquerychange" placeholder="Search Material" />
                    </div>
               </div>
               
               <div class="col-md-3">
                    <div class="form-group">
                         <label>Board type</label>
                         <select onchange="searchproduct();" id="boardtypechange">
                               <?php                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'material_type');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>
                    <div class="form-group">
                         <label>Product Name</label>
                         <select onchange="searchproduct();" id="pronamechange">
                              <option value="">--Please select a product--</option>
                              <?php if(count($products)>0){ ?>
                              <?php foreach($products as $product){
                                    $productid = $product->getId();
                               
                               ?>
                              <option value="<?php echo $productid; ?>"><?php echo $product->getName(); ?></option>
                              <?php } ?>
                              <?php } ?>
                         </select>
                    </div>
                    <div class="form-group">
                         <label>Manufacturer</label>
                         <select onchange="searchproduct();" id="manufacturerchange">
                              <?php                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'manufacturer');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>
                    <div class="form-group">
                         <label>Color</label>
                         <select onchange="searchproduct();" id="colorchange">
                              <?php                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'color');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>
                    
                    <div class="form-group">
                         <label>Thickness</label>
                         <select onchange="searchproduct();" id="thicknesschange">
                              <?php
                                   
                                   $attribute = $eavConfig->getAttribute('catalog_product', 'thickness');
                                   $options = $attribute->getSource()->getAllOptions();
                                                                      
                                   foreach($options as $option) { ?>
                                   <option value="<?php echo $option['value']; ?>"><?php echo $option['label']; ?></option>
                              <?php } ?>
                         </select>
                    </div>
                    
               </div>
               <div class="col-md-9">
                    <div class="product-listing" id="product-listing">
                         <div class="container">
                              <div class="row">
                                   <?php if(count($productslimit)>0){
                                        $imageHelper  = $om->get('\Magento\Catalog\Helper\Image');?>
                                   <?php foreach($productslimit as $product){
                                        $imageUrl = $imageHelper->init($product, 'product_page_image_medium')
                            ->constrainOnly(FALSE)
                            ->keepAspectRatio(TRUE)
                            ->keepFrame(FALSE)
                            ->resize(200, 200)
                            ->getUrl();
                              if (strpos($imageUrl, 'placeholder') !== false) {
                              $imageUrl = $this->getViewFileUrl('images/image.jpg');
                              }?>
                                   <div class="col-md-4 mb-5">
                                        <div class="proimage">
                                             <img src="<?php echo $imageUrl; ?>" alt="<?php echo $product->getName(); ?>" />
                                        </div>
                                       <span class="proname"><?php echo substr($product->getName(),0,50); ?></span>
                                       <button class="btn btn-secondary"><span onclick="addtocutlist(<?php echo $product->getId(); ?>);">Add to Cutlist</span></button>
                                   </div>
                                   <?php }} ?>
                              </div>
                         </div>
                    </div>
                    
               </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" id="closebtn" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



<style>
     .cutlist-table th{/*font-size: 12px; font-weight: normal;*/}
     #tpaneldescription{width: 30%}
</style>

<script type="text/javascript">
require([
    'jquery'
], function ($) {
$(document).ready(function(){
     $('#material').change(function(){
        var reviewUrl = 'https://perfectpanels.criticalmissioncomputing.co.uk/product.php';
        var proid = $(this).children("option:selected").val();
            $.ajax(reviewUrl, 
          {
              dataType: 'json', // type of response data
             // timeout: 500,     // timeout milliseconds
              data: { pro_id: proid },
              success: function (msg) {   // success callback function
               //console.log(msg);
               //document.getElementById("materialcode").innerHTML = $('#materialcode').append(msg.code);
               //$('#materialcode').val() = msg.code;
               document.getElementById("materialcode").value = msg.code;
               document.getElementById("length").value = msg.length;
               document.getElementById("width").value = msg.width;
               document.getElementById("paneldescription").value = msg.paneldescription;
               document.getElementById("thickness").value = msg.thickness;
               document.getElementById("sku").value = msg.sku;
               document.getElementById("proid").value = msg.proid;
               
               document.getElementById("tproductcode").innerHTML = msg.sku;
               document.getElementById("tmaterial").innerHTML = msg.code;
               document.getElementById("tlength").innerHTML = msg.length;
               document.getElementById("twidth").innerHTML = msg.width;
               document.getElementById("tpaneldescription").innerHTML = msg.paneldescription;

              }
          });
        });
     });

});


require([
    'jquery'
], function ($) {
$(document).ready(function(){
     $('.control input').keyup(function(){
          var valueid = $(this).attr('id');
          var valueattr = $(this).val();
          var newid = 't'+valueid;
          document.getElementById(newid).innerHTML = valueattr;
          //var valueid = $(this).val();
     });
   });  
});


//search on popupfunction
     function searchproduct(){
         var searchquery = jQuery('#searchquerychange').val();
         var boarddata = jQuery('#boardtypechange').val();
         var proid = jQuery('#pronamechange').val();
         var manufacturer = jQuery('#manufacturerchange').val();
         var color = jQuery('#colorchange').val();
         var thickness = jQuery('#thicknesschange').val();
         //alert(searchquery+boarddata+proid+manufacturer+color+thickness);
         document.getElementById("product-listing").innerHTML='<img style="margin-left:20%;margin-top:20%;" src="<?php echo $this->getViewFileUrl('images/loader-2.gif'); ?>" />'
	        jQuery.ajax({
		method: "POST",
		url: "https://perfectpanels.criticalmissioncomputing.co.uk/pro_search.php",
		data: { searchquery:searchquery,boarddata:boarddata,proid:proid,manufacturer:manufacturer,color:color,thickness: thickness}
		})
		.done(function( msgop ) {
		//alert(str);
               document.getElementById("product-listing").innerHTML= msgop;
		});
     }

// function after clicking add to cutlist button
     function addtocutlist(proid){
          var reviewUrl = 'https://perfectpanels.criticalmissioncomputing.co.uk/product.php';
          jQuery.ajax(reviewUrl, 
          {
              dataType: 'json', // type of response data
             // timeout: 500,     // timeout milliseconds
              data: { pro_id: proid },
              success: function (msg) {   // success callback function
               //console.log(msg);
               //document.getElementById("materialcode").innerHTML = $('#materialcode').append(msg.code);
               //$('#materialcode').val() = msg.code;
               document.getElementById("materialcode").value = msg.code;
               document.getElementById("length").value = msg.length;
               document.getElementById("width").value = msg.width;
               document.getElementById("paneldescription").value = msg.paneldescription;
               document.getElementById("thickness").value = msg.thickness;
               document.getElementById("sku").value = msg.sku;
               document.getElementById("proid").value = msg.proid;
               document.getElementById("material").value = msg.proid;
               
               
               document.getElementById("tproductcode").innerHTML = msg.sku;
               document.getElementById("tmaterial").innerHTML = msg.code;
               document.getElementById("tlength").innerHTML = msg.length;
               document.getElementById("twidth").innerHTML = msg.width;
               document.getElementById("tpaneldescription").innerHTML = msg.paneldescription;
               document.getElementById("closebtn").click();

              }
          });
          
          
     }

</script>