<?php

     if($this->getRequest()->getParam('id') !== NULL){
     $panelid = $this->getRequest()->getParam('id');
     $om = \Magento\Framework\App\ObjectManager::getInstance();
     $customerSession = $om->create('Magento\Customer\Model\Session');
     if($customerSession->isLoggedIn()) {
          $cusid =  $customerSession->getCustomer()->getId();
     }else{
          $cusid= 0;
     }
     $helper = $this->helper('pws\panel\Helper\Data');
     $values = $helper->getGroupListById($cusid);
     $panelinfo = $om->create('Pws\Panel\Model\Panel')->load($panelid);
     $panelname = $panelinfo->getName();
     $group_id = $panelinfo->getGroupId();
     $Position = $panelinfo->getPosition();
     $image = $panelinfo->getImage();
     
?>

<div class="blue-title-sec">
    <div class="container">              
        <div class="row align-items-center my-address-row">
          <div class="col-md-12 col-lg-4">
            <h2 class="mb-0"><?= $block->escapeHtml(__('Edit Project')) ?></h2>
          </div>
          <div class="col-md-12 col-lg-8">
          <p class="mb-0"><?= $block->escapeHtml(__('Please put the details of your project here')) ?></p>
          </div>
        </div>           
    </div>
</div>
<div class="main-content-sec grey-bg-sec">
<div class="container">
<div class="row justify-content-center">       
<div class="col-md-12 col-lg-8"> 
<div class="my-address-form">
<form class="form quickrfq"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="quickrfq_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" style="margin-bottom: 20px;">
        <legend class="legend"></legend><br />

        <!--<div class="field panel_group_id required form-group">
            <label for="panel_group_id"><?php /* @escapeNotVerified */ echo __('Your Panel Project:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
                <select name="group_id">
                   <?php if(count($values)>0){ ?>
                   <?php foreach($values as $key=>$name){ ?>
                   <option <?php if($group_id == $key){; ?>selected="selected"<?php } ?> value="<?php echo $key; ?>"><?php echo $name; ?></option>
                   <?php } ?>
                   <?php } ?>
                </select>
            </div>
        </div>-->
        
        <div class="field panel_image required form-group">
            <label for="panel_image"><?php /* @escapeNotVerified */ echo __('Your Project Name:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
                <input name="name" id="panel_name" title="<?php /* @escapeNotVerified */ echo __('Your Project Name:') ?>" value="<?php echo $panelname; ?>" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        
        <div class="field contact_name required form-group">
            <label for="contact_name"><?php /* @escapeNotVerified */ echo __('Upload Dxf. File:') ?></label>
            <div class="control">
                <input id="panel_image" name="image" data-ui-id="adminhtml-panel-edit-tab-main-0-fieldset-element-file-image" value="" title="Image" type="file" class="input-file">
                <?php if($image){ ?>
                <a target="blank" href="<?php echo $this->getUrl('pub/media').$image; ?>" title="View File">View File</a>
                <?php } ?>
            </div>
        </div>
        <!--<div class="field panel_position required form-group">
            <label for="panel_position"><?php /* @escapeNotVerified */ echo __('Want to keep your Offcuts?:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
                 <select name="position">
                    <option <?php if($Position==1):;echo 'selected="selected"';endif; ?> value="1">Yes</option>
                    <option <?php if($Position==0):;echo 'selected="selected"';endif; ?> value="0">No</option>
                 </select>
            </div>
        </div>-->

        <input type="hidden" name="url_key" value="<?php echo $cusid; ?>" />
        <input type="hidden" name="panel_id" value="<?php echo $panelid; ?>" />
        <input type="hidden" name="stores[]" value="0" />
        
    
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
      <div class="secondary">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn form-btn">
              <?php /* @escapeNotVerified */ echo __('Submit') ?>
            </button>
     </div>
      <?php if(isset($_SERVER['HTTP_REFERER'])){ ?>
          <div class="secondary form-btn-set ml-3"><a class="btn btn-outline-secondary" href="<?php echo $_SERVER['HTTP_REFERER']; ?>" title="Go back">Go Back</a></div>
     <?php } ?>
     </div>
</form>
</div>
</div>
</div>
</div>
</div>
<?php } ?>