<div class="blue-title-sec">
    <div class="container">              
        <div class="row align-items-center my-address-row">
          <div class="col-md-12 col-lg-4">
            <h2 class="mb-0"><?= $block->escapeHtml(__('Create Project')) ?></h2>
          </div>
          <div class="col-md-12 col-lg-8">
          <p class="mb-0"><?= $block->escapeHtml(__('Write the name of your project here')) ?></p>
          </div>
        </div>           
    </div>
</div>
<div class="main-content-sec grey-bg-sec">
<div class="container">
<div class="row justify-content-center">       
<div class="col-md-12 col-lg-8"> 
<div class="my-address-form">
<form class="form quickrfq"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="quickrfq_form"
      enctype="multipart/form-data"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" style="margin-bottom: 20px;">
        <legend class="legend"></legend><br />

        <div class="field contact_name required form-group">
            <label for="contact_name"><?php /* @escapeNotVerified */ echo __('Your Project Name:') ?><span style="color: red;">
            <?php /* @escapeNotVerified */ echo __('*') ?></span></label>
            <div class="control">
                <input name="name" id="panel_name" title="<?php /* @escapeNotVerified */ echo __('Your Project Name:') ?>" value="" class="form-control input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <?php
            $om = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $om->create('Magento\Customer\Model\Session');
            if($customerSession->isLoggedIn()) {
                $cusid =  $customerSession->getCustomer()->getId();
            }else{
                $cusid= 0;
            }
        ?>
        <input type="hidden" name="url_key" value="<?php echo $cusid; ?>" />
        
    
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
      <div class="secondary">
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="btn form-btn">
              <?php /* @escapeNotVerified */ echo __('Submit') ?>
            </button>
     </div>
      <?php if($_SERVER['HTTP_REFERER'] !== NULL){ ?>
        <div class="secondary form-btn-set ml-3"><a class="btn btn-outline-secondary" href="<?php echo $_SERVER['HTTP_REFERER']; ?>" title="Go back">Go Back</a></div>
        <?php } ?>
      </div>
</form>
</div>
</div>
</div>
</div>
</div>